### ISSUE TITLE
oaieval command failure

### ISSUE THREAD

**Issue by desojo** [Significant-Gravitas/Auto-GPT-Benchmarks#14]
Command: VALS_THREADS=1 EVALS_THREAD_TIMEOUT=600 oaieval auto_gpt_completion_fn test-match --registry_path $PWD/auto_gpt_benchmarking

Output: 

```
[2023-04-19 06:03:18,322] [registry.py:249] Loading registry from /opt/homebrew/lib/python3.9/site-packages/evals/registry/evals
[2023-04-19 06:03:18,380] [registry.py:249] Loading registry from /Users/ejohnson/.evals/evals
[2023-04-19 06:03:18,380] [registry.py:249] Loading registry from /Users/ejohnson/src/Auto-GPT-Benchmarks/auto_gpt_benchmarking/auto_gpt_benchmarking/evals
[2023-04-19 06:03:19,041] [registry.py:249] Loading registry from /opt/homebrew/lib/python3.9/site-packages/evals/registry/completion_fns
[2023-04-19 06:03:19,045] [registry.py:249] Loading registry from /Users/ejohnson/.evals/completion_fns
[2023-04-19 06:03:19,045] [registry.py:249] Loading registry from /Users/ejohnson/src/Auto-GPT-Benchmarks/auto_gpt_benchmarking/auto_gpt_benchmarking/completion_fns
[2023-04-19 06:03:19,045] [registry.py:120] completion_fn 'auto_gpt_completion_fn' not found. Closest matches: []
Traceback (most recent call last):
  File "/opt/homebrew/bin/oaieval", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/evals/cli/oaieval.py", line 164, in main
    run(args)
  File "/opt/homebrew/lib/python3.9/site-packages/evals/cli/oaieval.py", line 72, in run
    completion_fn_instances = [registry.make_completion_fn(url) for url in completion_fns]
  File "/opt/homebrew/lib/python3.9/site-packages/evals/cli/oaieval.py", line 72, in <listcomp>
    completion_fn_instances = [registry.make_completion_fn(url) for url in completion_fns]
  File "/opt/homebrew/lib/python3.9/site-packages/evals/registry.py", line 106, in make_completion_fn
    raise ValueError(f"Could not find CompletionFn in the registry with ID {name}")
ValueError: Could not find CompletionFn in the registry with ID auto_gpt_completion_fn
```

**Comment by samuelbutler** [comment]
This line of your output looks like this isn't being run in a virtual env
`[2023-04-19 06:03:19,041] [registry.py:249] Loading registry from /opt/homebrew/lib/python3.9/site-packages/evals/registry/completion_fns`

That means the eval scripts can't find the `benchmarking.pth` file that you should have created in `/Users/ejohnson/src/Auto-GPT-Benchmarks/venv/lib/python3.9/site-packages/benchmarking.pth` after you created an activated a Python virtual environment named `venv`.

The contents of that `benchmarking.pth` file should be `/Users/ejohnson/src/Auto-GPT-Benchmarks/` for your system.

That should resolve this error.

**Comment by desojo** [comment]
Hmm, that is what the contents of benchmarking.pth happens to be, but it's throwing the same error.

**Comment by samuelbutler** [comment]
even in a virtual environment? can you post your error output again while running this in a venv?

I had this same error and was able to resolve it which is what makes me think this isn't a bug.

**Comment by dschonholtz** [comment]
@desojo and @samuelbutler These guys should be resolved now. 
Thanks for taking an initial crack at it when it was still really, really unstable.

**Comment by dschonholtz** [comment]
I am closing this, as this is no longer how we run benchmarks
